USE MMNTeam;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS Users;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE Users(
  user_id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(40) NOT NULL,
  surname VARCHAR(40) NOT NULL,
  username VARCHAR(40) NOT NULL,
  password VARCHAR(120) NOT NULL,
  email VARCHAR(50) NOT NULL,
  state VARCHAR(50) NOT NULL
);
